export default [
	"Frakkland eða Lýðveldið Frakkland, (franska République française eða France) er land í Vestur-Evrópu sem nær frá Miðjarðarhafi í suðri að Ermarsundi í norðri og frá Rín í austri að Atlantshafi í vestri. Vegna lögunar landsins gengur það oft undir heitinu „sexhyrningurinn“ (fr. Hexagone) hjá Frökkum sjálfum. Í Evrópu á Frakkland landamæri að Belgíu, Lúxemborg, Þýskalandi, Sviss, Ítalíu, Mónakó, Spáni og Andorra, en handanhafssýslur þess í öðrum heimsálfum eiga landamæri að Brasilíu, Súrínam og Hollensku Antillaeyjum. Landið tengist Bretlandseyjum gegnum Ermarsundsgöngin.",
	"Frakkland er meðal aðildarríkja Evrópusambandsins og Atlantshafsbandalagsins og á fast sæti í Öryggisráði Sameinuðu þjóðanna",
	"Landamæri Frakklands í Evrópu eru 2970 km að lengd og snúa að eftirtöldum átta ríkjum: Spáni (650 km), Belgíu (620 km), Sviss (572 km), Ítalíu (515 km), Þýskalandi (450 km), Lúxemborg (73 km), Andorra (57 km) og Mónakó (4,5 km). Í Suður-Ameríku á Franska Gíana landamæri að Brasilíu (580 km) og Súrínam (520 km). Saint-Martin-ey í Antillaeyjaklasanum skiptist milli Frakklands og Hollands. Loks gera Frakkar tilkall til svonefndrar Terre Adélie á Suðurskautslandinu. Stjórnsýsla á þessum yfirráðasvæðum Frakklands er með ýmsum hætti og ganga þau eftir því undir fjölbreytilegum nöfnum, allt frá „handanhafssýslu“ til „handanhafssvæðis“.",
	"Meginland Frakklands einkennist af mjög fjölbreyttu landslagi, allt frá flatlendinu með norður- og vesturströndinni að fjallakeðjunum í suðaustri (Ölpunum) og suðvestri (Pýreneafjöllum). Í frönsku Ölpunum er hæsti fjallstindur í vestanverðri Evrópu, Mont Blanc, sem er talinn 4810 m. Í landinu er víða fjalllendi sem er eldra að uppruna, til að mynda miðhálendið (Massif Central), Júrafjöll, Vogesafjöll og loks Ardennafjöll sem eru bæði klettótt og vaxin þéttum skógi. Frakkar njóta þess einnig að eiga mikið kerfi vatnsfalla en helstu fljótin eru Leira, Rón (kemur upp í Sviss), Garonne (kemur upp á Spáni), Signa og nokkur hluti árinnar Rín, en einnig Somme og Vilaine. Meuse er eina stórfljótið í Frakklandi sem hefur ekki verið aðlagað skipaumferð.",
	"Landsvæði Frakklands í Evrópu er 544 000 km², en með svæðunum utan Evrópu fer sú tala upp í 640 000.",
	"Vegna mikils fjölda franskra yfirráðasvæða um allan heim sem snúa að hafi ræður Frakkland yfir annarri stærstu efnahagslögsögu heims á eftir Bandaríkjunum, samtals mælist hún 11.035.000 km².",
	"Frakkland nútímans tekur yfir svipað svæði og hið forna hérað Gallía þar sem Gallar bjuggu en þeir voru keltnesk þjóð. Á fyrstu öld fyrir Krist var Gallía innlimuð í Rómaveldi og tóku íbúarnir upp latneska tungu og menningu. Kristni skaut rótum í landinu á annarri og þriðju öld eftir Krist. Á fjórðu öld tóku germanskir ættflokkar að streyma yfir Rín sem markaði austurlandamæri Gallíu. Í þeim hópi voru Frankar mest áberandi en af þeim er nafn Frakklands dregið.",
	"Samfelld tilvist Frakklands sem sérstaks ríkis er talin hefjast á 9. öld þegar Frankaveldi Karlamagnúsar skiptist í vestur- og austurhluta. Austurhlutinn náði þá yfir það svæði sem nú er Þýskaland og er þessi skipting oft einnig talin marka upphaf Þýskalands.",
	"Normannar lögðu undir sig England árið 1066 sem síðar leiddi til togstreitu milli afkomenda Vilhjálms Sigurvegara hertoga af Normandí og konunga Frakklands í hinu svokallaða hundrað ára stríði.",
];
